name: test container

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish container
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tez-capital/tezpay
          dockerfile: ./container/Containerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platform: linux/amd64,linux/arm64
