name: build tezpay 

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
      - name: Build generated docs
        run: go run ./docs/build/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Docs Generation

      - name: clone builder
        uses: actions/checkout@v3
        env:
          SSH_DEPLOY_KEY: ${{ secrets.ACCESS_DOCS_BUILDER }}
        with:
          path: docs-builder
          repository: tez-capital/docs.tez.capital_builder
          ssh-key: $SSH_DEPLOY_KEY
      
      - name: inject tp docs
        run: |
          # command reference

          rm -rf docs-builder/content/reusable/tezpay/cmd/*
          mkdir -p docs-builder/content/reusable/tezpay/cmd/
          export CWD=$PWD
          cd docs/cmd
          for f in *.md; do 
            echo "Processing $f file..."; 
            (echo "---";
            echo "title: $(printf $f | cut -d. -f1)";
            echo "weight: 3";
            echo "type: docs";
            echo "---") | \
            cat - $f > $CWD/docs-builder/content/reusable/tezpay/cmd/$f
          done
          cd ../..

          # configuration samples
          rm -rf docs-builder/content/reusable/tezpay/configuration/*
          mkdir -p docs-builder/content/reusable/tezpay/configuration/
          cd docs/configuration
          for f in config.*.hjson; do 
            echo "Processing $f file..."; 
            (echo "---";
            echo "title: $(printf $f | cut -d. -f2)";
            echo "weight: 3";
            echo "type: docs";
            echo "summary: tezpay $(printf $f | cut -d. -f2) configuration";
            echo "---";
            echo '```yaml') | \
            cat - $f > $CWD/docs-builder/content/reusable/tezpay/configuration/$(printf $f | cut -d. -f2).md
            (echo ''; echo '```') >> $CWD/docs-builder/content/reusable/tezpay/configuration/$(printf $f | cut -d. -f2).md
          done
          cd ../..

      - name: Get current date
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: update-builder
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.ACCESS_DOCS_BUILDER }}
          GITHUB_SHA: $GITHUB_SHA 
        with:
          source-directory: docs-builder/
          destination-github-username: tez-capital
          destination-repository-name: docs.tez.capital_builder
          user-email: docs-builder@tez.capital
          commit-message: publish-${{ steps.date.outputs.date }}
          target-branch: tezpay-${{ steps.date.outputs.date }}
